// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewPost struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Post struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Query struct {
}

type UpdatePost struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}
